### ISSUE TITLE
Single-file header-only HxA loader

### ISSUE THREAD

**Issue by raysan5** [quelsolaar/HxA#8]
Hi, I'd like to support HxA models loading in raylib. All the file-formats loading libraries I use are always single-file header-only, would be possible to have a similar loader for HxA file-format?

I think it would be very useful for maximum portability.

**Comment by quelsolaar** [comment]
Single header file implementations are more of a C++ thing then a C thing. The hxa.h file acts as a specification for the format. Loading the file version of HxA is not really required for some uses of the conventions so i would like to keep them separate. However, HxA is designed to be as trivial as possible to implement, so a header only C++ version would probably be a good thing to have. I however is a terrible C++ programmer so I'm probably not the right person to write it. If there is any way i can help you make the current C version easier to integrate let me know!!

**Comment by raysan5** [comment]
Thanks for your quick answer! :D

Actually I'm more used to [C single-header files](https://github.com/raysan5/raylib/tree/master/src/external) than C++, that's probably because C is the language I use. As you can see in the list, several 3d-model-format loaders are provided as a C single-header library, that makes them really easy to integrate in any engine.

In any case, I keep an eye on the repo in case you consider that possibility in a future.

**Comment by quelsolaar** [comment]
Maybe we could do a merge of the basic loader with the HxA .h file specificly for this purpose. That should be easy. Would that help?

**Comment by raysan5** [comment]
@quelsolaar Sure! That would be perfect!
